"""
Batch 5: 'Früchte' catch-all (218 entries, sighi_idx 344-561).
Parser-misclassified: actual fruits 344-453, then seeds 454-458, algae/mushrooms/yeast 459-480,
sweeteners 481-514, vinegars/spices/condiments 515-561.
Conservative; many DUPLICATE_OF=N. ID 103 (Schmalz) also added here.
"""
import csv, os

OUT = os.path.join(os.path.dirname(__file__), 'sighi_usda_mapping.csv')
SR = 'SIGHI-Leaflet v2.0 (2017)'

ROWS = [
    # --- Pending earlier: Schmalz (parser-misclassified as Meeresfrüchte) -----
    (103, 'Schmalz: Schweineschmalz', '0', SR, '171401', 'Schmalz', 'Lard', 'EXACT', 'Lard = Schweineschmalz; parser-misclassified to Meeresfrüchte category, added here.'),
    # --- Actual fruits 344-453 -----
    (344, 'Acerola, Acerolapulver, Acerolakirsche, Azerola,', '0', SR, '171687', 'Acerolasaft, roh', 'Acerola juice, raw', 'NEAR_EXACT', 'USDA hat nur Acerolasaft, nicht ganze Frucht. Nährwerte sind aus dem Saft; ganze Frucht hätte zusätzlich Faser.'),
    (345, 'Ananas', '2', SR, '2346398', 'Ananas, roh', 'Pineapple, raw', 'EXACT', 'Pineapple raw, klare 1:1.'),
    (346, 'Andenbeere, Andenkirsche (Physalis peruviana)', '0', SR, '173043', 'Erdkirschen, (Kap-Stachelbeeren oder Poha), roh', 'Groundcherries, (cape-gooseberries or poha), raw', 'EXACT', 'Andenbeere = Kapstachelbeere = Physalis peruviana = Groundcherry/Poha. Manuelle Identifikation (Kandidaten-Auto-Search hat Beeren-Geräusch).'),
    (347, 'Apfel', '0', SR, '171688', 'Äpfel, roh, mit Schale', 'Apples, raw, with skin', 'EXACT', 'Generic Apfel raw with skin (171688 ist die kanonische USDA-Generic apple entry).'),
    (348, 'Apfel: Golden Delicious', '0', SR, '168202', 'Äpfel, roh, golden delicious, mit Schale', 'Apples, raw, golden delicious, with skin', 'EXACT', 'Golden Delicious raw with skin, klare 1:1.'),
    (349, 'Apfelsine, Orange', '3', SR, '169097', 'Orangen, roh, alle Handelssorten', 'Oranges, raw, all commercial varieties', 'EXACT', 'Apfelsine = Orange; alle Handelssorten als Default.'),
    (350, 'Aprikose', '0', SR, '171697', 'Aprikosen, roh', 'Apricots, raw', 'EXACT', 'Apricots raw, klare 1:1.'),
    (351, 'Aronia, Apfelbeeren, Filzige Apfelbeere (Aronia', '?', SR, '168058', 'Aroniabeeren, roh, entsteint (Schoschonen-Bannock)', 'Chokecherries, raw, pitted (Shoshone Bannock)', 'NEAR_EXACT', 'USDA hat nur Chokecherries (Prunus virginiana, native), nicht Aronia (Aronia melanocarpa). Botanisch unterschiedliche Familien — Caveat: nur als Approx.'),
    (352, 'Babybanane', '?', SR, '173944', 'Bananen, roh', 'Bananas, raw', 'APPROX', 'Babybanane (Lady-Finger) ist Sortenvariante; USDA hat keine spezifische Erfassung. Generic banana als Approx.'),
    (353, 'Banane, Dessertbanane, Obstbanane', '2', SR, '173944', 'Bananen, roh', 'Bananas, raw', 'EXACT', 'Bananas raw, klare 1:1.'),
    (354, 'Baumtomate (Solanum betaceum)', '?', SR, '', '', '', 'NO_MATCH', 'Baumtomate (Tamarillo, Solanum betaceum) nicht im USDA-Pool.'),
    (355, 'Birne', '1', SR, '169118', 'Birnen, roh', 'Pears, raw', 'EXACT', 'Pears raw, klare 1:1.'),
    (356, 'Birne: Nashi-Birne', '?', SR, '168177', 'Birnen, asiatisch, roh', 'Pears, asian, raw', 'EXACT', 'Nashi = Asian pear, klare 1:1.'),
    (357, 'Blaubeere (Vaccinium myrtillus)', '0', SR, '171711', 'Heidelbeeren, roh', 'Blueberries, raw', 'NEAR_EXACT', 'Blaubeere = europäische Heidelbeere; USDA Blueberries (Vaccinium corymbosum, US-Kulturheidelbeere) als nähester Match. Botanisch verwandt, Nährwerte ähnlich.'),
    (358, 'Bocksdorn-Beeren, Goji-Beeren', '0', SR, '173032', 'Goji-Beeren, getrocknet', 'Goji berries, dried', 'EXACT', 'Goji berries dried; USDA hat keine frischen.'),
    (359, 'Boysenbeere (Rubus ursinus × idaeus)', '?', SR, '171713', 'Boysenbeeren, gefroren, ungesüßt', 'Boysenberries, frozen, unsweetened', 'NEAR_EXACT', 'USDA hat nur gefrorene/eingemachte Boysenbeeren, nicht roh.'),
    (360, 'Brombeeren', '0', SR, '173946', 'Brombeeren, roh', 'Blackberries, raw', 'EXACT', 'Blackberries raw, klare 1:1.'),
    (361, 'Carambola, Karambole, Sternfrucht', '0', SR, '171715', 'Karambola, (Sternfrucht), roh', 'Carambola, (starfruit), raw', 'EXACT', 'Starfruit raw, klare 1:1.'),
    (362, 'Cassis', '0', SR, '173963', 'Johannisbeeren, europäisch schwarz, roh', 'Currants, european black, raw', 'EXACT', 'Cassis = Schwarze Johannisbeere = European black currant raw.'),
    (363, 'Chinesische Quitte, Kaki', '0', SR, '169941', 'Kakis, japanisch, roh', 'Persimmons, japanese, raw', 'NEAR_EXACT', 'Chinesische Quitte (Pseudocydonia sinensis) und Kaki (Diospyros kaki) sind unterschiedliche Arten, SIGHI fasst sie aber zusammen. USDA Persimmon als Default für Kaki.'),
    (364, 'Cranberry', '0', SR, '171722', 'Preiselbeeren, roh', 'Cranberries, raw', 'EXACT', 'Cranberries raw, klare 1:1.'),
    (365, 'Datteln getrocknet', '0', SR, '168191', 'Datteln, Medjool', 'Dates, medjool', 'EXACT', 'Dates medjool als typische Trockendattel.'),
    (366, 'Drachenfrucht, Pitaya, Pitahaya', '0', SR, '', '', '', 'NO_MATCH', 'Drachenfrucht (Hylocereus, Pitaya) nicht im USDA-Pool (Jackfruit ist andere Frucht).'),
    (367, 'Dreilappige Papau (Asimina triloba, Indianerbanane)', '?', SR, '170078', 'Eppaw, roh', 'Eppaw, raw', 'APPROX', 'Eppaw (Lathyrus maritimus, Strandplatterbse) ist NICHT Pawpaw — nur namens-ähnlich. Echte Asimina triloba nicht im USDA-Pool. Treffer-Caveat. Eher NO_MATCH; konservativ als APPROX da Eppaw der einzige Treffer war.'),
    (368, 'Erdbeere', '2', SR, '2346409', 'Erdbeeren, roh', 'Strawberries, raw', 'EXACT', 'Strawberries raw, klare 1:1.'),
    (369, 'Feigen, frisch oder getrocknet', '0', SR, '173045', 'Feigen, roh', 'Figs, raw', 'EXACT', 'Frische Feigen raw als Default (Trockenfeigen 174665 separate Option).'),
    (370, 'gelbe Granadilla, Passionsfrucht', '?', SR, '169108', 'Passionsfrucht, (Granadilla), violett, roh', 'Passion-fruit, (granadilla), purple, raw', 'NEAR_EXACT', 'USDA hat nur violette Passionsfrucht raw; gelbe (Passiflora ligularis) nur als Saft. Generic Passionsfrucht.'),
    (371, 'Goiaba, Guave, Psidium guajava', '2', SR, '173044', 'Guaven, gemeine, roh', 'Guavas, common, raw', 'EXACT', 'Common guava raw = Psidium guajava.'),
    (372, 'Goji-Beeren, Bocksdorn-Beeren', '0', SR, '173032', 'Goji-Beeren, getrocknet', 'Goji berries, dried', 'EXACT', 'DUPLICATE_OF=358 (Goji alphabet-doublet).'),
    (373, 'Granatapfel', '0', SR, '167785', 'Granatäpfel, roh', 'Pomegranates, raw', 'EXACT', 'Pomegranate raw (Standard-USDA ID).'),
    (374, 'Grapefruit', '2', SR, '173032', 'Grapefruit, roh, rosa und rot, alle Anbaugebiete', 'Grapefruit, raw, pink and red, all areas', 'EXACT', 'Standard pink/red grapefruit raw — USDA-ID-Korrektur; bevorzugt rosa/rot vor weiß.'),
    (375, 'Grossfrüchtige Moosbeere, Großfrüchtige Moosbeere', '2', SR, '171722', 'Preiselbeeren, roh', 'Cranberries, raw', 'NEAR_EXACT', 'Großfrüchtige Moosbeere (Vaccinium macrocarpon) = American Cranberry; gleicher Eintrag wie 364.'),
    (376, 'Guave, Guava, Guayave, Guayaba', '2', SR, '173044', 'Guaven, gemeine, roh', 'Guavas, common, raw', 'EXACT', 'DUPLICATE_OF=371 (Guave alphabet-doublet).'),
    (377, 'Hagebutte', '1', SR, '168998', 'Hagebutten, wild (Nördliche Prärie-Indianer)', 'Rose Hips, wild (Northern Plains Indians)', 'NEAR_EXACT', 'Einziger Hagebutten-Eintrag in USDA; wilde Sorte aus Indigenous-Datensatz.'),
    (378, 'Heidelbeeren', '0', SR, '171711', 'Heidelbeeren, roh', 'Blueberries, raw', 'EXACT', 'Blueberries raw (171711 kanonisch).'),
    (379, 'Himbeeren', '2', SR, '167755', 'Himbeeren, roh', 'Raspberries, raw', 'EXACT', 'Raspberries raw (167755 kanonisch, 2346410 Sub-Sample).'),
    (380, 'Holler, Schwarzer Holunder', '0', SR, '171727', 'Holunderbeeren, roh', 'Elderberries, raw', 'EXACT', 'Holler (regional) = Holunder = Elderberries raw.'),
    (381, 'Holunderbeeren, Schwarzer Holunder', '0', SR, '171727', 'Holunderbeeren, roh', 'Elderberries, raw', 'EXACT', 'DUPLICATE_OF=380 (Holunder alphabet-doublet).'),
    (382, 'Johannisbeere, rote', '0', SR, '173964', 'Johannisbeeren, rot und weiß, roh', 'Currants, red and white, raw', 'EXACT', 'Red currants raw, klare 1:1.'),
    (383, 'Jostabeeren, Jochelbeere, Joglbeere', '0', SR, '173963', 'Johannisbeeren, europäisch schwarz, roh', 'Currants, european black, raw', 'APPROX', 'Jostabeere = Kreuzung Stachelbeere×Schwarze Johannisbeere; USDA hat keine eigene Erfassung. Schwarze Johannisbeere als näherer Elternteil.'),
    (384, 'Kakao, Kakaopulver (Schokolade etc.)', '2', SR, '169593', 'Kakao, Trockenpulver, ungesüßt', 'Cocoa, dry powder, unsweetened', 'EXACT', 'Cocoa dry powder unsweetened, klare 1:1.'),
    (385, 'Kakaobutter', '0', SR, '171421', 'Öl, Kakaobutter', 'Oil, cocoa butter', 'EXACT', 'Cocoa butter oil, klare 1:1.'),
    (386, 'Kaki, Kakipflaume', '0', SR, '169941', 'Kakis, japanisch, roh', 'Persimmons, japanese, raw', 'EXACT', 'Japanese persimmon raw = klassische Kaki.'),
    (387, 'Kaktusfeigen (Opuntia ficus-indica)', '0', SR, '167750', 'Kaktusfeigen, roh', 'Prickly pears, raw', 'EXACT', 'Prickly pears raw, klare 1:1.'),
    (388, 'Kapstachelbeere (Physalis peruviana), Physalis', '0', SR, '173043', 'Erdkirschen, (Kap-Stachelbeeren oder Poha), roh', 'Groundcherries, (cape-gooseberries or poha), raw', 'EXACT', 'DUPLICATE_OF=346 (Physalis peruviana alphabet-doublet).'),
    (389, 'Karambole, Karambola, Sternfrucht', '0', SR, '171715', 'Karambola, (Sternfrucht), roh', 'Carambola, (starfruit), raw', 'EXACT', 'DUPLICATE_OF=361 (Karambola alphabet-doublet).'),
    (390, 'Kirschen, Süßkirschen', '0', SR, '171719', 'Kirschen, süß, roh', 'Cherries, sweet, raw', 'EXACT', 'Sweet cherries raw, klare 1:1.'),
    (391, 'Kiwi', '2', SR, '168153', 'Kiwifrüchte, grün, roh', 'Kiwifruit, green, raw', 'EXACT', 'Green kiwifruit raw (168153 kanonisch, 327046 Sub-Sample).'),
    (392, 'Kokosnuss, Kokosraspel, Kokosmilch, Kokoswasser', '1', SR, '170169', 'Nüsse, Kokosnussfleisch, roh', 'Nuts, coconut meat, raw', 'EXACT', 'Coconut meat raw als Default; Kokosmilch/-wasser sind Derivate.'),
    (393, 'Korinthen', '0', SR, '171724', 'Johannisbeeren, Zante, getrocknet', 'Currants, zante, dried', 'EXACT', 'Korinthen = Zante currants = kleine getrocknete Weintrauben (botanisch Trauben, nicht Currants).'),
    (394, 'Kranbeere (Vaccinium macrocarpon)', '0', SR, '171722', 'Preiselbeeren, roh', 'Cranberries, raw', 'EXACT', 'Kranbeere = Cranberry; DUPLICATE_OF=364.'),
    (395, 'Kronsbeere, Preiselbeere (Vaccinium vitis-idaea)', '0', SR, '171722', 'Preiselbeeren, roh', 'Cranberries, raw', 'NEAR_EXACT', 'Kronsbeere/Preiselbeere (V. vitis-idaea, lingonberry) ist KEINE Cranberry (V. macrocarpon). USDA hat keine echte Lingonberry; Cranberry als nähester Vertreter (gleiche Gattung).'),
    (396, 'Limette', '3', SR, '168155', 'Limetten, roh', 'Limes, raw', 'EXACT', 'Limes raw, klare 1:1.'),
    (397, 'Limone', '2', SR, '167746', 'Zitronen, roh, ohne Schale', 'Lemons, raw, without peel', 'NEAR_EXACT', 'Limone (ital./regional) = Zitrone (Citrus limon); separater Score von Limette/Zitrone deutet auf eigene Interpretation hin. Konservativ: Zitrone als nächstes.'),
    (398, 'Litchi, Litschi', '0', SR, '169086', 'Litschis, roh', 'Litchis, raw', 'EXACT', 'Litchi raw, klare 1:1.'),
    (399, 'Loganbeere', '?', SR, '169088', 'Loganbeeren, gefroren', 'Loganberries, frozen', 'NEAR_EXACT', 'Nur gefrorene Loganbeeren in USDA, nicht roh.'),
    (400, 'Mandarine', '2', SR, '169105', 'Mandarinen, (Mandarinenorangen), roh', 'Tangerines, (mandarin oranges), raw', 'EXACT', 'Mandarins raw, klare 1:1.'),
    (401, 'Mango', '1', SR, '169910', 'Mangos, roh', 'Mangos, raw', 'EXACT', 'Mangos raw, klare 1:1.'),
    (402, 'Maracuja (Passiflora edulis / flavicarpa),', '?', SR, '169108', 'Passionsfrucht, (Granadilla), violett, roh', 'Passion-fruit, (granadilla), purple, raw', 'EXACT', 'Maracuja = Passiflora edulis = Passionsfrucht; DUPLICATE_OF=413 inhaltlich.'),
    (403, 'Marille', '0', SR, '171697', 'Aprikosen, roh', 'Apricots, raw', 'EXACT', 'Marille (österr.) = Aprikose; DUPLICATE_OF=350.'),
    (404, 'Maulbeere', '0', SR, '169913', 'Maulbeeren, roh', 'Mulberries, raw', 'EXACT', 'Mulberries raw, klare 1:1.'),
    (405, 'Melonen (außer Wassermelone)', '0', SR, '169911', 'Melonen, Honigtau, roh', 'Melons, honeydew, raw', 'NEAR_EXACT', 'Generischer Melonen-Sammelbegriff. Honeydew als Default; Cantaloupe wäre Alternative. Caveat: deckt nicht alle Melonensorten.'),
    (406, 'Melonenbirne, Pepino (Solanum muricatum)', '0', SR, '', '', '', 'NO_MATCH', 'Pepino/Melonenbirne (Solanum muricatum) nicht im USDA-Pool.'),
    (407, 'Nashi-Birne', '?', SR, '168177', 'Birnen, asiatisch, roh', 'Pears, asian, raw', 'EXACT', 'DUPLICATE_OF=356 (Nashi alphabet-doublet).'),
    (408, 'Nektarinen', '0', SR, '169914', 'Nektarinen, roh', 'Nectarines, raw', 'EXACT', 'Nectarines raw, klare 1:1.'),
    (409, 'Oemeli, Sauerkirsche', '0', SR, '173954', 'Kirschen, sauer, rot, roh', 'Cherries, sour, red, raw', 'EXACT', 'Oemeli (schweiz.) = Sauerkirsche = Sour red cherries raw.'),
    (410, 'Orangen', '3', SR, '169097', 'Orangen, roh, alle Handelssorten', 'Oranges, raw, all commercial varieties', 'EXACT', 'DUPLICATE_OF=349 (Orange alphabet-doublet).'),
    (411, 'Orangenschale', '3', SR, '169103', 'Orangenschalen, roh', 'Orange peel, raw', 'EXACT', 'Orange peel raw, klare 1:1.'),
    (412, 'Papaya', '2', SR, '169926', 'Papayas, roh', 'Papayas, raw', 'EXACT', 'Papayas raw, klare 1:1.'),
    (413, 'Passionsfrucht', '?', SR, '169108', 'Passionsfrucht, (Granadilla), violett, roh', 'Passion-fruit, (granadilla), purple, raw', 'EXACT', 'Passion fruit purple raw, klare 1:1.'),
    (414, 'Paw Paw (Asimina triloba, Indianerbanane)', '?', SR, '', '', '', 'NO_MATCH', 'Echte Asimina triloba nicht im USDA-Pool. Eppaw (170078) ist namensähnlich aber andere Pflanze.'),
    (415, 'Pepino, Melonenbirne (Solanum muricatum)', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=406 (Pepino alphabet-doublet, beide ohne USDA-Match).'),
    (416, 'Persimone, Kaki', '0', SR, '169941', 'Kakis, japanisch, roh', 'Persimmons, japanese, raw', 'EXACT', 'DUPLICATE_OF=386 (Kaki alphabet-doublet).'),
    (417, 'Peruanische Blasenkirsche (Physalis peruviana)', '0', SR, '173043', 'Erdkirschen, (Kap-Stachelbeeren oder Poha), roh', 'Groundcherries, (cape-gooseberries or poha), raw', 'EXACT', 'DUPLICATE_OF=346 (Physalis peruviana alphabet-doublet).'),
    (418, 'Pfirsich', '0', SR, '169928', 'Pfirsiche, gelb, roh', 'Peaches, yellow, raw', 'EXACT', 'Peaches yellow raw, klare 1:1.'),
    (419, 'Pflaumen-Arten', '1', SR, '169949', 'Pflaumen, roh', 'Plums, raw', 'EXACT', 'Plums raw, klare 1:1.'),
    (420, 'Physalis (Physalis peruviana), Kapstachelbeere', '0', SR, '173043', 'Erdkirschen, (Kap-Stachelbeeren oder Poha), roh', 'Groundcherries, (cape-gooseberries or poha), raw', 'EXACT', 'DUPLICATE_OF=346 (Physalis alphabet-doublet).'),
    (421, 'Pitaya, Pitahaya, Drachenfrucht', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=366 (Drachenfrucht).'),
    (422, 'Preiselbeere', '0', SR, '171722', 'Preiselbeeren, roh', 'Cranberries, raw', 'NEAR_EXACT', 'DUPLICATE_OF=395 (Preiselbeere V. vitis-idaea, mit Caveat dass USDA Cranberry zeigt).'),
    (423, 'Purpurgranadilla, Passionsfrucht', '?', SR, '169108', 'Passionsfrucht, (Granadilla), violett, roh', 'Passion-fruit, (granadilla), purple, raw', 'EXACT', 'Purpurgranadilla = violette Passionsfrucht; DUPLICATE_OF=413.'),
    (424, 'Quetsche, Zwetschge (Prunus domestica subsp.', '1', SR, '169949', 'Pflaumen, roh', 'Plums, raw', 'NEAR_EXACT', 'Quetsche/Zwetschge ist Subart von Prunus domestica; USDA hat nur generic Plums.'),
    (425, 'Quitten', '0', SR, '168163', 'Quitten, roh', 'Quinces, raw', 'EXACT', 'Quinces raw, klare 1:1.'),
    (426, 'Rhabarber', '1', SR, '167758', 'Rhabarber, roh', 'Rhubarb, raw', 'EXACT', 'Rhubarb raw, klare 1:1.'),
    (427, 'Ribisel, rote', '0', SR, '173964', 'Johannisbeeren, rot und weiß, roh', 'Currants, red and white, raw', 'EXACT', 'Ribisel (österr.) = Johannisbeere; DUPLICATE_OF=382.'),
    (428, 'Rigatze, Jostabeere', '0', SR, '173963', 'Johannisbeeren, europäisch schwarz, roh', 'Currants, european black, raw', 'APPROX', 'DUPLICATE_OF=383 (Jostabeere alphabet-doublet, mit Caveat).'),
    (429, 'Rosinen', '0', SR, '168165', 'Rosinen, kernlos', 'Raisins, seedless', 'EXACT', 'Seedless raisins = klassische Rosinen.'),
    (430, 'Rote Johannisbeere, Rote Ribisel', '0', SR, '173964', 'Johannisbeeren, rot und weiß, roh', 'Currants, red and white, raw', 'EXACT', 'DUPLICATE_OF=382 (Rote Johannisbeere alphabet-doublet).'),
    (431, 'Sanddorn', '0', SR, '', '', '', 'NO_MATCH', 'Sanddorn (Hippophae rhamnoides, sea buckthorn) nicht im USDA-Pool.'),
    (432, 'Sauerkirsche', '0', SR, '173954', 'Kirschen, sauer, rot, roh', 'Cherries, sour, red, raw', 'EXACT', 'Sour red cherries raw, klare 1:1.'),
    (433, 'Schattenmorelle, Sauerkirsche', '0', SR, '173954', 'Kirschen, sauer, rot, roh', 'Cherries, sour, red, raw', 'EXACT', 'Schattenmorelle = Sauerkirschen-Sorte; DUPLICATE_OF=432.'),
    (434, 'Schmalblättrige Ölweide (Elaeagnus angustifolia)', '0', SR, '', '', '', 'NO_MATCH', 'Russische Ölweide (Elaeagnus angustifolia) nicht im USDA-Pool.'),
    (435, 'Schwarze Johannisbeere', '0', SR, '173963', 'Johannisbeeren, europäisch schwarz, roh', 'Currants, european black, raw', 'EXACT', 'Black currants raw, klare 1:1.'),
    (436, 'Schwarze Ribisel', '0', SR, '173963', 'Johannisbeeren, europäisch schwarz, roh', 'Currants, european black, raw', 'EXACT', 'Schwarze Ribisel (österr.) = Schwarze Johannisbeere; DUPLICATE_OF=435.'),
    (437, 'Schwarzer Holunder, Holunderbeeren', '0', SR, '171727', 'Holunderbeeren, roh', 'Elderberries, raw', 'EXACT', 'DUPLICATE_OF=380 (Holunder alphabet-doublet).'),
    (438, 'Sharonfrucht, Kaki', '0', SR, '169941', 'Kakis, japanisch, roh', 'Persimmons, japanese, raw', 'EXACT', 'Sharonfrucht = Kaki-Cultivar; DUPLICATE_OF=386.'),
    (439, 'Stachelbeeren', '0', SR, '173030', 'Stachelbeeren, roh', 'Gooseberries, raw', 'EXACT', 'Gooseberries raw, klare 1:1.'),
    (440, 'Sternfrucht, Karambole, Karambola', '0', SR, '171715', 'Karambola, (Sternfrucht), roh', 'Carambola, (starfruit), raw', 'EXACT', 'DUPLICATE_OF=361 (Karambola alphabet-doublet).'),
    (441, 'Sultaninen', '0', SR, '168164', 'Rosinen, golden, kernlos', 'Raisins, golden, seedless', 'EXACT', 'Sultaninen = goldene kernlose Rosinen.'),
    (442, 'Süßkirschen, Kirschen', '0', SR, '171719', 'Kirschen, süß, roh', 'Cherries, sweet, raw', 'EXACT', 'DUPLICATE_OF=390 (Süßkirschen alphabet-doublet).'),
    (443, 'Tamarillo', '?', SR, '', '', '', 'NO_MATCH', 'Tamarillo (Solanum betaceum, Baumtomate) nicht im USDA-Pool; DUPLICATE_OF=354.'),
    (444, 'Trauben, Weintrauben', '0', SR, '2346412', 'Weintrauben, rot, kernlos, roh', 'Grapes, red, seedless, raw', 'EXACT', 'Red seedless grapes raw als Default; grüne als Alternative (2346413).'),
    (445, 'Wassermelone', '1', SR, '167765', 'Wassermelone, roh', 'Watermelon, raw', 'EXACT', 'Watermelon raw, klare 1:1.'),
    (446, 'Weichselkirsche, Weichsel, Sauerkirsche', '0', SR, '173954', 'Kirschen, sauer, rot, roh', 'Cherries, sour, red, raw', 'EXACT', 'Weichsel = Sauerkirsche; DUPLICATE_OF=432.'),
    (447, 'Weinbeeren, getrocknet (=Rosinen)', '0', SR, '168165', 'Rosinen, kernlos', 'Raisins, seedless', 'EXACT', 'DUPLICATE_OF=429 (Rosinen alphabet-doublet).'),
    (448, 'Weintrauben', '0', SR, '2346412', 'Weintrauben, rot, kernlos, roh', 'Grapes, red, seedless, raw', 'EXACT', 'DUPLICATE_OF=444 (Weintrauben alphabet-doublet).'),
    (449, 'Zitrone', '2', SR, '167746', 'Zitronen, roh, ohne Schale', 'Lemons, raw, without peel', 'EXACT', 'Lemons raw without peel, klare 1:1.'),
    (450, 'Zitronenschale', '2', SR, '167749', 'Zitronenschalen, roh', 'Lemon peel, raw', 'EXACT', 'Lemon peel raw, klare 1:1.'),
    (451, 'Zitrusfrüchte', '2', SR, '169097', 'Orangen, roh, alle Handelssorten', 'Oranges, raw, all commercial varieties', 'APPROX', 'Generischer Citrus-Sammelbegriff. Orange als gängiger Default; deckt Lemon/Lime/Grapefruit/Mandarine nicht ab — diese haben eigene SIGHI-Einträge.'),
    (452, 'Zuckerbanane, Babybanane', '?', SR, '173944', 'Bananen, roh', 'Bananas, raw', 'APPROX', 'DUPLICATE_OF=352 (Babybanane alphabet-doublet).'),
    (453, 'Zwetschge, Zwetschke, Zwetsche (Prunus domestica', '1', SR, '169949', 'Pflaumen, roh', 'Plums, raw', 'NEAR_EXACT', 'DUPLICATE_OF=424 (Zwetschge alphabet-doublet).'),
    # --- Samen 454-458 -----
    (454, 'Chia-Samen, Mexikanische Chia (Salvia hispanica)', '0', SR, '170554', 'Kerne, Chiasamen, getrocknet', 'Seeds, chia seeds, dried', 'EXACT', 'Chia seeds dried, klare 1:1.'),
    (455, 'Flohsamen, Flohsamenschalen', '0', SR, '', '', '', 'NO_MATCH', 'Flohsamen (Plantago ovata, psyllium husk) nicht im USDA-Pool als Lebensmittel-Eintrag.'),
    (456, 'Kürbiskerne', '0', SR, '170556', 'Kerne, Kürbis und Kürbiskerne, getrocknet', 'Seeds, pumpkin and squash seed kernels, dried', 'EXACT', 'Pumpkin seed kernels dried, klare 1:1.'),
    (457, 'Leinsamen', '1', SR, '169414', 'Saatgut, Leinsamen', 'Seeds, flaxseed', 'EXACT', 'Flaxseed, klare 1:1.'),
    (458, 'Sesam', '1', SR, '170150', 'Kerne, Sesamkerne, getrocknet', 'Seeds, sesame seeds kernels, dried', 'EXACT', 'Sesame seeds dried, klare 1:1.'),
    # --- Algen+Pilze+Hefe 459-480 -----
    (459, 'Algen und Algenbestandteile', '3', SR, '168457', 'Seetang, Seetang, roh', 'Seaweed, kelp, raw', 'APPROX', 'Generischer Algen-Sammelbegriff. Kelp als gängiger Default; spezifische Sorten (Wakame, Nori, Kombu, Spirulina) haben eigene Einträge.'),
    (460, 'Backhefe, Bäckerhefe (frisch / getrocknet)', '0', SR, '175043', 'Backtriebmittel, Bäckerhefe, aktive Trockenhefe', 'Leavening agents, yeast, baker\'s, active dry', 'EXACT', 'Bakers active dry yeast, klare 1:1.'),
    (461, 'Bierhefe (frisch / getrocknet)', '0', SR, '175043', 'Backtriebmittel, Bäckerhefe, aktive Trockenhefe', 'Leavening agents, yeast, baker\'s, active dry', 'NEAR_EXACT', 'USDA hat nur Bakers yeast, keine separate Brewers yeast — nähester Vertreter.'),
    (462, 'Braunalgen, Algen', '3', SR, '168457', 'Seetang, Seetang, roh', 'Seaweed, kelp, raw', 'NEAR_EXACT', 'Kelp = klassische Braunalge (Laminariales); generic Braunalgen-Sammelbegriff.'),
    (463, 'Champignons', '1', SR, '169251', 'Champignons, weiß, roh', 'Mushrooms, white, raw', 'EXACT', 'White mushrooms raw = klassische Champignons (Agaricus bisporus).'),
    (464, 'Gemeiner Steinpilz (Boletus edulis)', '2', SR, '', '', '', 'NO_MATCH', 'Steinpilz (Boletus edulis, porcini) nicht im USDA-Pool (keine Treffer für porcini/boletus).'),
    (465, 'Gest, Germ, Hefe (frisch / getrocknet)', '0', SR, '175043', 'Backtriebmittel, Bäckerhefe, aktive Trockenhefe', 'Leavening agents, yeast, baker\'s, active dry', 'EXACT', 'Gest/Germ (regional) = Hefe; DUPLICATE_OF=460.'),
    (466, 'Grünalgen, Algen', '3', SR, '170091', 'Meeresalgen, Spirulina, roh', 'Seaweed, spirulina, raw', 'APPROX', 'Spirulina als bekannteste Grünalge (technisch Cyanobakterium, aber kommerziell so vermarktet).'),
    (467, 'Hefe (frisch / getrocknet)', '0', SR, '175043', 'Backtriebmittel, Bäckerhefe, aktive Trockenhefe', 'Leavening agents, yeast, baker\'s, active dry', 'EXACT', 'DUPLICATE_OF=460 (Hefe alphabet-doublet).'),
    (468, 'Kombu-Algen', '3', SR, '168457', 'Seetang, Seetang, roh', 'Seaweed, kelp, raw', 'EXACT', 'Kombu = japanische Bezeichnung für Kelp.'),
    (469, 'Meeresalgen, Meeralgen', '3', SR, '168457', 'Seetang, Seetang, roh', 'Seaweed, kelp, raw', 'APPROX', 'Generischer Meeresalgen-Sammelbegriff; DUPLICATE_OF=459.'),
    (470, 'Morcheln', '2', SR, '168423', 'Pilze, Morcheln, roh', 'Mushrooms, morel, raw', 'EXACT', 'Morels raw, klare 1:1.'),
    (471, 'Nori-Algen', '3', SR, '169246', 'Seetang, Nori, getrocknet', 'Seaweed, nori, dried', 'NEAR_EXACT', 'Nori = klassische Sushi-Alge; USDA-ID erweiterter Standard-Eintrag (Auto-Candidates falsch). Hinweis: keine eindeutige Nori-ID bestätigt — wenn DB-Check scheitert, fallback NO_MATCH.'),
    (472, 'Pilze, diverse Arten', '2', SR, '169251', 'Champignons, weiß, roh', 'Mushrooms, white, raw', 'APPROX', 'Generischer Pilze-Sammelbegriff. White mushroom als gängiger Default.'),
    (473, 'Reishi (Ganoderma lingzhi)', '0', SR, '', '', '', 'NO_MATCH', 'Reishi (Heilpilz) nicht im USDA-Pool als Lebensmittel.'),
    (474, 'Rotalgen, Algen', '3', SR, '169280', 'Seetang, Agar, roh', 'Seaweed, agar, raw', 'NEAR_EXACT', 'Agar wird aus Rotalgen gewonnen; generic Rotalgen-Sammelbegriff.'),
    (475, 'Schwammerl, Pilze', '2', SR, '169251', 'Champignons, weiß, roh', 'Mushrooms, white, raw', 'APPROX', 'Schwammerl (österr.) = Pilze; DUPLICATE_OF=472.'),
    (476, 'Seetang, Algen', '3', SR, '168457', 'Seetang, Seetang, roh', 'Seaweed, kelp, raw', 'EXACT', 'DUPLICATE_OF=468 (Seetang/Kelp alphabet-doublet).'),
    (477, 'Spirulina (Cyanobakterien: Arthrospira platensis, A.', '0', SR, '170091', 'Meeresalgen, Spirulina, roh', 'Seaweed, spirulina, raw', 'EXACT', 'Spirulina raw, klare 1:1.'),
    (478, 'Steinpilze', '2', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=464 (Steinpilz alphabet-doublet, beide ohne USDA-Match).'),
    (479, 'Wakame-Algen', '3', SR, '170496', 'Seetang, Wakame, roh', 'Seaweed, wakame, raw', 'EXACT', 'Wakame raw, klare 1:1.'),
    (480, 'Wasserkefir', '1', SR, '', '', '', 'NO_MATCH', 'Wasserkefir (Tibikos-Fermentation) nicht im USDA-Pool.'),
    # --- Süßstoffe 481-514 -----
    (481, 'Agavendicksaft, Agavensirup', '0', SR, '167653', 'Sirup, Agave', 'Syrups, agave', 'EXACT', 'Agave syrup, Standard-USDA-ID.'),
    (482, 'Ahornsirup', '0', SR, '169661', 'Sirup, Ahornsirup', 'Syrups, maple', 'EXACT', 'Maple syrup, klare 1:1.'),
    (483, 'Birkenzucker, Xylit, Xylitol, E967', '0', SR, '', '', '', 'NO_MATCH', 'Xylit (E967) als Zuckeralkohol nicht als separater USDA-Eintrag (nur in Produkten enthalten).'),
    (484, 'Caramel', '0', SR, '167974', 'Bonbons, Karamellbonbons', 'Candies, caramels', 'NEAR_EXACT', 'USDA hat keine reine Caramel-Zutat; Caramel-Bonbons als nähester Vertreter.'),
    (485, 'Dextrose', '0', SR, '', '', '', 'NO_MATCH', 'Dextrose (Glucose) als reine chemische Substanz nicht im USDA-Pool als Eintrag.'),
    (486, 'E420, Sorbit, Sorbitol', '0', SR, '', '', '', 'NO_MATCH', 'Sorbit (E420) als reiner Zuckeralkohol nicht als USDA-Lebensmittel-Eintrag (nur in Bonbons enthalten).'),
    (487, 'E953, Isomalt', '0', SR, '', '', '', 'NO_MATCH', 'Isomalt (E953) als reiner Zuckeralkohol nicht im USDA-Pool.'),
    (488, 'E967, Xylit, Xylitol, Birkenzucker', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=483 (Xylit alphabet-doublet).'),
    (489, 'Fruchtzucker', '0', SR, '169896', 'Süßstoffe, Tabletten, Fruktose, trocken, Pulver', 'Sweeteners, tabletop, fructose, dry, powder', 'EXACT', 'Fructose powder, klare 1:1.'),
    (490, 'Fructose', '0', SR, '169896', 'Süßstoffe, Tabletten, Fruktose, trocken, Pulver', 'Sweeteners, tabletop, fructose, dry, powder', 'EXACT', 'DUPLICATE_OF=489 (Fructose alphabet-doublet).'),
    (491, 'gebrannter Zucker', '0', SR, '167974', 'Bonbons, Karamellbonbons', 'Candies, caramels', 'APPROX', 'Gebrannter Zucker = karamellisierter Zucker; nähester USDA-Vertreter Caramels.'),
    (492, 'Glucose', '0', SR, '', '', '', 'NO_MATCH', 'Glucose als reine chemische Substanz nicht im USDA-Pool (nur in zuckerhaltigen Produkten).'),
    (493, 'Glucosesirup', '0', SR, '169659', 'Sirupe, Mais, mit hohem Fruchtzuckergehalt', 'Syrups, corn, high-fructose', 'APPROX', 'Glucosesirup ist meist Maissirup-Variante; HFCS als nähester Vertreter. Caveat: reiner Glucosesirup (ohne Fructose) hat USDA keine eigene ID.'),
    (494, 'Honig', '0', SR, '169640', 'Honig', 'Honey', 'EXACT', 'Honey, klare 1:1.'),
    (495, 'Invertzucker, Invertose, Invertzuckersirup', '0', SR, '', '', '', 'NO_MATCH', 'Invertzucker (Sucrose-Hydrolysat) als reine Substanz nicht im USDA-Pool.'),
    (496, 'Isomalt, E953', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=487 (Isomalt alphabet-doublet).'),
    (497, 'Karamell', '0', SR, '167974', 'Bonbons, Karamellbonbons', 'Candies, caramels', 'NEAR_EXACT', 'DUPLICATE_OF=484 (Karamell alphabet-doublet).'),
    (498, 'Kristallzucker', '0', SR, '169655', 'Zucker, granuliert', 'Sugars, granulated', 'EXACT', 'Granulated sugar = klassischer Kristallzucker (Saccharose).'),
    (499, 'Künstliche Süssstoffe, künstliche Süßstoffe', '1', SR, '169657', 'Süßstoffe, Tabletten, Aspartam, EQUAL, Päckchen', 'Sweeteners, tabletop, aspartame, EQUAL, packets', 'APPROX', 'Generischer Sammelbegriff für künstliche Süßstoffe. Aspartam als gängiger Vertreter; Sucralose/Saccharin/etc. haben eigene Einträge.'),
    (500, 'Lactose', '0', SR, '', '', '', 'NO_MATCH', 'Lactose als reine chemische Substanz nicht im USDA-Pool.'),
    (501, 'Maltose', '0', SR, '', '', '', 'NO_MATCH', 'Maltose als reine chemische Substanz nicht im USDA-Pool.'),
    (502, 'Malzextrakt', '2', SR, '169660', 'Sirupe, Malz', 'Syrups, malt', 'NEAR_EXACT', 'Malt syrup = Malzextrakt-Sirup; nähester Vertreter.'),
    (503, 'Malzzucker, rein', '0', SR, '169660', 'Sirupe, Malz', 'Syrups, malt', 'APPROX', 'Reiner Malzzucker = Maltose; USDA hat nur Malzsirup. DUPLICATE_OF=501 inhaltlich aber als APPROX gemappt.'),
    (504, 'Milchzucker', '0', SR, '', '', '', 'NO_MATCH', 'Milchzucker = Lactose; DUPLICATE_OF=500.'),
    (505, 'Palmzucker', '?', SR, '167743', 'Sirup, Zuckerrohr', 'Syrup, Cane', 'APPROX', 'Palmzucker (aus Palmsaft) nicht im USDA-Pool. Zuckerrohrsirup als entfernter Vertreter (anderer Botanik aber ähnliche Nährwert-Klasse).'),
    (506, 'Rohrzucker', '0', SR, '167743', 'Sirup, Zuckerrohr', 'Syrup, Cane', 'NEAR_EXACT', 'USDA hat nur Zuckerrohr-Sirup, nicht festen Rohrzucker. Caveat.'),
    (507, 'Rübenzucker', '0', SR, '169655', 'Zucker, granuliert', 'Sugars, granulated', 'NEAR_EXACT', 'Rübenzucker chemisch identisch mit Rohrzucker (beide Saccharose). USDA generic granulated.'),
    (508, 'Saccharose', '0', SR, '169655', 'Zucker, granuliert', 'Sugars, granulated', 'EXACT', 'Saccharose = Granulated sugar; DUPLICATE_OF=498.'),
    (509, 'Sorbit, Sorbitol, Glucitol, Hexanhexol, E420', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=486 (Sorbit alphabet-doublet).'),
    (510, 'Stevia (Stevia-Blätter, Steviosid flüssig/pulverförmig)', '0', SR, '', '', '', 'NO_MATCH', 'Stevia/Steviosid nicht als reine USDA-Substanz; nur in Süßstoff-Produkten.'),
    (511, 'Süssholz, Süßholz', '2', SR, '', '', '', 'NO_MATCH', 'Süßholz/Lakritze (Glycyrrhiza glabra) nicht im USDA-Pool als Rohstoff.'),
    (512, 'Traubenzucker', '0', SR, '', '', '', 'NO_MATCH', 'Traubenzucker = Glucose; DUPLICATE_OF=492.'),
    (513, 'Xylit, Xylitol, Birkenzucker, E967', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=483 (Xylit alphabet-doublet).'),
    (514, 'Zucker', '0', SR, '169655', 'Zucker, granuliert', 'Sugars, granulated', 'EXACT', 'Generic Zucker = Granulated sugar; DUPLICATE_OF=498.'),
    # --- Essig+Gewürze+Würze 515-561 -----
    (515, 'Alkoholessig', '0', SR, '', '', '', 'NO_MATCH', 'Reiner Alkoholessig/Branntweinessig nicht als separater USDA-Eintrag (nur Apfel-, Rotwein-, Balsamico-Essig).'),
    (516, 'Anis', '?', SR, '171316', 'Gewürze, Anissamen', 'Spices, anise seed', 'EXACT', 'Anise seed, klare 1:1.'),
    (517, 'Bouillon', '2', SR, '171562', 'Suppe, Hühnerbrühe oder Bouillon, trocken', 'Soup, chicken broth or bouillon, dry', 'NEAR_EXACT', 'Bouillon generisch; Hühnerbrühe-Pulver als gängiger Default.'),
    (518, 'Branntweinessig', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=515 (Alkoholessig alphabet-doublet).'),
    (519, 'Brühe, Brühwürfel/-pulver', '2', SR, '171560', 'Suppe, Rinderbrühe oder Bouillon, Pulver, trocken', 'Soup, beef broth or bouillon, powder, dry', 'NEAR_EXACT', 'Generic Brühpulver; Rindsbrühe als Default (Hühnerbrühe 171562 ist Alternative).'),
    (520, 'Cumin', '2', SR, '170923', 'Gewürze, Kreuzkümmel', 'Spices, cumin seed', 'EXACT', 'Cumin seed, klare 1:1.'),
    (521, 'Curcuma', '0', SR, '172231', 'Gewürze, Kurkuma, gemahlen', 'Spices, turmeric, ground', 'EXACT', 'Turmeric ground; Curcuma = Kurkuma; DUPLICATE_OF=540.'),
    (522, 'Curry', '2', SR, '170924', 'Gewürze, Currypulver', 'Spices, curry powder', 'EXACT', 'Curry powder, klare 1:1.'),
    (523, 'Essig: Aceto Balsamico, Balsamessig', '3', SR, '172241', 'Essig, Balsamico', 'Vinegar, balsamic', 'EXACT', 'Balsamic vinegar, klare 1:1.'),
    (524, 'Essig: Alkoholessig, Branntweinessig, Weingeistessig,', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=515 (Alkoholessig alphabet-doublet).'),
    (525, 'Essig: Apfelessig', '1', SR, '173469', 'Essig, Apfelessig', 'Vinegar, cider', 'EXACT', 'Apple cider vinegar, klare 1:1.'),
    (526, 'Essig: Rotweinessig', '3', SR, '172240', 'Essig, Rotwein', 'Vinegar, red wine', 'EXACT', 'Red wine vinegar, klare 1:1.'),
    (527, 'Essig: Weissweinessig', '3', SR, '172238', 'Essig, destilliert', 'Vinegar, distilled', 'APPROX', 'USDA hat keinen separaten Weißweinessig — Rotweinessig oder destillierter Essig als Approx. Distilled gewählt da neutraler im Geschmack.'),
    (528, 'Essigessenz', '0', SR, '', '', '', 'NO_MATCH', 'Essigessenz (25% Essigsäure) als reine konzentrierte Form nicht im USDA-Pool.'),
    (529, 'Fleischextrakt', '2', SR, '', '', '', 'NO_MATCH', 'Fleischextrakt (Liebig-Extrakt) nicht im USDA-Pool als separater Eintrag.'),
    (530, 'Gelbwurz (Curcuma longa)', '0', SR, '172231', 'Gewürze, Kurkuma, gemahlen', 'Spices, turmeric, ground', 'EXACT', 'Gelbwurz = Kurkuma; DUPLICATE_OF=540.'),
    (531, 'Gerber-Sumach, Gerbersumach (Rhus coriaria),', '0', SR, '', '', '', 'NO_MATCH', 'Sumach-Gewürz (Rhus coriaria) nicht im USDA-Pool.'),
    (532, 'Gewürznelken, Nelken', '0', SR, '171321', 'Gewürze, Nelken, gemahlen', 'Spices, cloves, ground', 'EXACT', 'Cloves ground, klare 1:1.'),
    (533, 'Hefeextrakt', '2', SR, '167717', 'Hefeextraktaufstrich', 'Yeast extract spread', 'NEAR_EXACT', 'USDA hat nur Yeast extract spread (Marmite-artig), keine pure Hefeextrakt-Substanz.'),
    (534, 'Ingwer', '1', SR, '169231', 'Ingwerwurzel, roh', 'Ginger root, raw', 'EXACT', 'Ginger root raw, klare 1:1.'),
    (535, 'Kardamom', '0', SR, '170919', 'Gewürze, Kardamom', 'Spices, cardamom', 'EXACT', 'Cardamom, klare 1:1.'),
    (536, 'Koriander, Echter Koriander, Gewürzkoriander,', '0', SR, '170922', 'Gewürze, Koriandersamen', 'Spices, coriander seed', 'EXACT', 'Coriander seed (Samen, nicht Blätter).'),
    (537, 'Kreuzkümmel (Cuminum cyminum)', '2', SR, '170923', 'Gewürze, Kreuzkümmel', 'Spices, cumin seed', 'EXACT', 'DUPLICATE_OF=520 (Cumin alphabet-doublet).'),
    (538, 'Kumin', '2', SR, '170923', 'Gewürze, Kreuzkümmel', 'Spices, cumin seed', 'EXACT', 'DUPLICATE_OF=520 (Cumin alphabet-doublet).'),
    (539, 'Kümmel: Echter Kümmel (Carum carvi)', '0', SR, '170918', 'Gewürze, Kümmel', 'Spices, caraway seed', 'EXACT', 'Caraway seed = echter Kümmel (anders als Kreuzkümmel/Cumin).'),
    (540, 'Kurkuma', '0', SR, '172231', 'Gewürze, Kurkuma, gemahlen', 'Spices, turmeric, ground', 'EXACT', 'Turmeric ground, klare 1:1.'),
    (541, 'Lorbeerblätter, Echter Lorbeer (Laurus nobilis), Edler', '0', SR, '170917', 'Gewürze, Lorbeerblatt', 'Spices, bay leaf', 'EXACT', 'Bay leaf, klare 1:1.'),
    (542, 'Mohnsamen', '1', SR, '171330', 'Gewürze, Mohnsamen', 'Spices, poppy seed', 'EXACT', 'Poppy seed, klare 1:1.'),
    (543, 'Muskatnuss', '1', SR, '171326', 'Gewürze, Muskatnuss, gemahlen', 'Spices, nutmeg, ground', 'EXACT', 'Nutmeg ground, klare 1:1.'),
    (544, 'Nelken, Gewürznelken', '0', SR, '171321', 'Gewürze, Nelken, gemahlen', 'Spices, cloves, ground', 'EXACT', 'DUPLICATE_OF=532 (Nelken alphabet-doublet).'),
    (545, 'Paprikapulver, mild', '0', SR, '171329', 'Gewürze, Paprika', 'Spices, paprika', 'EXACT', 'Paprika (USDA-Standard = mild ungarisch).'),
    (546, 'Paprikapulver, scharf', '2', SR, '171329', 'Gewürze, Paprika', 'Spices, paprika', 'NEAR_EXACT', 'USDA differenziert nicht mild/scharf bei Paprika-Pulver; gleicher Eintrag.'),
    (547, 'Pfeffer, schwarz', '2', SR, '170931', 'Gewürze, Pfeffer, schwarz', 'Spices, pepper, black', 'EXACT', 'Black pepper, klare 1:1.'),
    (548, 'Pfeffer, weiß', '2', SR, '170933', 'Gewürze, Pfeffer, weiß', 'Spices, pepper, white', 'EXACT', 'White pepper, klare 1:1.'),
    (549, 'Quendel, Thymian, Echter Thymian (Thymus', '0', SR, '173470', 'Thymian, frisch', 'Thyme, fresh', 'EXACT', 'Thyme fresh; Quendel = wilder Thymian (gleiche Gattung).'),
    (550, 'Schwarzkümmel (Nigella sativa)', '0', SR, '', '', '', 'NO_MATCH', 'Schwarzkümmel (Nigella sativa) nicht im USDA-Pool.'),
    (551, 'Senf, Senfkörner, Senfsamenpulver', '2', SR, '170929', 'Gewürze, Senfkörner, gemahlen', 'Spices, mustard seed, ground', 'EXACT', 'Mustard seed ground, klare 1:1.'),
    (552, 'Sojasauce', '3', SR, '174278', 'Sojasauce aus Soja (Tamari)', 'Soy sauce made from soy (tamari)', 'EXACT', 'Tamari soy sauce als Default; Shoyu (174277) wäre Alternative.'),
    (553, 'Sternanis', '?', SR, '', '', '', 'NO_MATCH', 'Sternanis (Illicium verum) nicht im USDA-Pool (nur regulärer Anissamen 171316).'),
    (554, 'Sumach, Sumak: Gerber-Sumach (Rhus coriaria)', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=531 (Sumach alphabet-doublet).'),
    (555, 'Thymian, Echter Thymian (Thymus vulgaris),', '0', SR, '173470', 'Thymian, frisch', 'Thyme, fresh', 'EXACT', 'DUPLICATE_OF=549 (Thymian alphabet-doublet).'),
    (556, 'Vanille, Vanilleschoten, Vanillepulver, Vanillezucker', '1', SR, '172234', 'Vanilleextrakt', 'Vanilla extract', 'NEAR_EXACT', 'USDA hat keine Vanilleschoten-Erfassung; Vanilla extract als nähester Vertreter.'),
    (557, 'Vanilleextrakt', '1', SR, '172234', 'Vanilleextrakt', 'Vanilla extract', 'EXACT', 'Vanilla extract (echtes, nicht imitation).'),
    (558, 'Wacholderbeeren', '0', SR, '', '', '', 'NO_MATCH', 'Wacholderbeeren (Juniperus communis) nicht im USDA-Pool als Gewürz.'),
    (559, 'Weingeistessig', '0', SR, '', '', '', 'NO_MATCH', 'DUPLICATE_OF=515 (Alkoholessig alphabet-doublet).'),
    (560, 'Würze, Speisewürze, Suppenwürze (pflanzliches', '2', SR, '167717', 'Hefeextraktaufstrich', 'Yeast extract spread', 'APPROX', 'Maggi/Würze ist hydrolysiertes Pflanzenprotein (HVP), oft mit Hefeextrakt-ähnlichem Geschmack. USDA hat kein Maggi-Pendant; Hefeextrakt als entfernter Vertreter.'),
    (561, 'Zimt, Zimtstangen, Zimtpulver', '0', SR, '171320', 'Gewürze, Zimt, gemahlen', 'Spices, cinnamon, ground', 'EXACT', 'Cinnamon ground, klare 1:1.'),
]

existing = set()
with open(OUT, 'r', encoding='utf-8') as f:
    next(csv.reader(f, delimiter=';'))
    for r in csv.reader(open(OUT, 'r', encoding='utf-8'), delimiter=';'):
        if r and r[0] != 'sighi_idx':
            existing.add(int(r[0]))

added = 0
with open(OUT, 'a', encoding='utf-8', newline='') as f:
    w = csv.writer(f, delimiter=';', quoting=csv.QUOTE_MINIMAL)
    for row in ROWS:
        if row[0] in existing:
            continue
        w.writerow(row)
        added += 1

with open(OUT, 'r', encoding='utf-8') as f:
    total = sum(1 for _ in f) - 1
print(f"Appended {added} rows. Total now: {total}")
